version: "3"
services:
  blog-app:
    container_name: blog-app-container_name
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"

volumes: postgres-db
