FROM node:18 as base

FROM base as development

WORKDIR /app
COPY package.json . 
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm" ,"RUN" ,"start-dev" ]

FROM base as production

WORKDIR /app
COPY package.json . 
RUN npm install --only=production
COPY . .
EXPOSE 3000
CMD [ "npm" ,"RUN" ,"start-dev" ]
